### ISSUE TITLE
How to set up Endpoint for params in url?

### ISSUE THREAD

**Issue by martinjinda** [tomaj/nette-api#39]
I haven't found an example how to add a new endpoint for the variable parameter in URL. Example url: `/api/v1/users/$id`.

I think it's a trivial thing.

**Comment by tomaj** [comment]
This is possible, but it is not trivial :-(

you have to register custom route in nette RouterFactory, like this:

```
$router[] = new Route('/api/v1/users/<id>', [
            'module' => 'Api',
            'presenter' => 'Api',
            'action' => 'default',
            'version' => 1,
            'package' => 'users',
            'apiAction' => 'detail',
]);
``

**Comment by martinjinda** [comment]
I use /users path for getting all users and now I think I have a conflict and I'm still getting _Unknown api endpoint_.

**Comment by tomaj** [comment]
You should try to register this route without <id> also

**Comment by martinjinda** [comment]
Did you try it? I see a similar example in the readme. I try almost every option and I can't read the parameter from the url :(

**Comment by tomaj** [comment]
I've used this in one project

```
$router = new RouteList;
$router[] = new Route('/api/v2/bookmarks/top', [
    'module' => 'Api',
    'presenter' => 'Api',
    'action' => 'default',
    'version' => 2,
    'package' => 'bookmarks',
    'apiAction' => 'top',
]);
$router[] = new Route('/api/v2/bookmarks/<id>', [
    'module' => 'Api',
    'presenter' => 'Api',
    'action' => 'default',
    'version' => 2,
    'package' => 'bookmarks',
    'apiAction' => 'detail',
]);
$router[] = new Route('/api/v<version>/<package>[/<apiAction>][/<params>]', 'Api:Api:default');
$router[] = new Route('<module>/<presenter>/<action>[/<id>]', 'Admin:Dashboard:default');
$router[] = new Route('<presenter>/<action>[/<id>]', 'Admin:Dashboard:default');
```

and for the parsing id i have to get it from url in handler
```
$parts = explode('/', $this->request->getUrl()->getPath());
$id = array_pop($parts);
```

and `$this->request` is `Nette\Http\Request` instance injected via constructor from di

**Comment by martinjinda** [comment]
I'm still getting _Unknown api endpoint_. I will post code maybe you will see what's my problem. If not I will try it in a different way. 

My UserDetailHandler.php:

```
  class UsersDetailHandler extends BaseHandler
  {
    
    private $userRepository;
    private $request;
    
    function __construct(UsersRepository $usersRepository, Request $request)
    {
      parent::__construct();
      
      $this->userRepository = $usersRepository;
      $this->request = $request;
    }
    
    public function handle($params)
    {
      
      $parts = explode(
        '/', $this->request->getUrl()
        ->getPath()
      );
      
      $id = array_pop($parts);
      
      return new JsonApiResponse(
        200, [
          'status' => 'ok',
          'users'  => $id
        ]
      );
    }
  }
```
RouterFactory

 ```
$router = new RouteList;
      
      $router[] = new Route('/api/v1/users/<id>', [
        'module' => 'Api',
        'presenter' => 'Api',
        'action' => 'default',
        'version' => 1,
        'package' => 'users',
        'apiAction' => 'detail',
      ]);
      
      $router[] = new Route('/api/v<version>/<package>[/<apiAction>][/<params>]', 'Api:Api:default');
      $router[] = new Route('<presenter>/<action>[/<id>]', 'Homepage:default');
      
      return $router;
```

config.neon
```
    apiDecider:
        class: Tomaj\NetteApi\ApiDecider
        setup:
            - addApiHandler(\Tomaj\NetteApi\EndpointIdentifier('POST', 1, 'users'), \App\Api\v1\Handlers\UsersAddingHandler(), \Tomaj\NetteApi\Authorization\NoAuthorization())
            - addApiHandler(\Tomaj\NetteApi\EndpointIdentifier('DELETE', 1, 'users'), \App\Api\v1\Handlers\UsersDeletingHandler(), \Tomaj\NetteApi\Authorization\NoAuthorization())
```
